#!/usr/bin/env python3
"""Emit paper/figures/best_achievable.tex: per-game best-achievable F/T/L under held-out
(leave-one-seed-out) decoder selection, plus the best-L-vs-best-T verdict. Re-run after the
decoder grid finishes to auto-fill all 7 games."""
import os, sys
import numpy as np
from scipy import stats

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from decoder_select_cv import load, heldout_mean, GAMES  # reuse the validated protocol

DECLABEL = {"greedy": "greedy", "t0.3": r"$\tau$0.3", "t0.5": r"$\tau$0.5",
            "t0.7": r"$\tau$0.7", "t1.0": r"$\tau$1.0", "t1.5": r"$\tau$1.5"}

def mode_pick(picks):
    if not picks: return "--"
    from collections import Counter
    lab = Counter(l for _, l in picks).most_common(1)[0][0]
    return DECLABEL.get(lab, lab)

def main():
    rows = []
    for name, tag in GAMES:
        dec = load(tag)
        if not dec:
            rows.append((name, None)); continue
        cell = {}
        for s in ["F", "T", "L"]:
            ho, picks = heldout_mean(dec, s)
            cell[s] = (float(np.mean(ho)) if len(ho) else float("nan"), mode_pick(picks), ho)
        L, T = cell["L"][2], cell["T"][2]
        if len(L) and len(T):
            p = stats.ttest_ind(L, T, equal_var=False).pvalue
            u = stats.mannwhitneyu(L, T, alternative="two-sided").pvalue
            # compute the displayed % from the rounded means we actually print, so the
            # table is internally self-consistent (matters for floor cells like Enduro).
            mL, mT = round(np.mean(L)), round(np.mean(T))
            dm = 100 * (mL - mT) / mT if mT else float("nan")
            if np.mean(L) > np.mean(T) and min(p, u) < 0.05:   v = r"\textbf{L}"
            elif np.mean(T) > np.mean(L) and min(p, u) < 0.05: v = r"\textbf{T}"
            else:                                              v = "tie"
            cell["verdict"] = (v, dm, min(p, u))
        rows.append((name, cell))

    lines = [r"% Auto-generated by scripts/make_best_achievable_table.py — do not edit by hand.",
             r"\begin{tabular}{lccccl}", r"\toprule",
             r"Game & best $F$ & best $T$ & best $L$ & $\Delta_{L-T}$ & winner \\",
             r"     & (decoder) & (decoder) & (decoder) & (\%, $p$) & \\", r"\midrule"]
    for name, c in rows:
        if c is None:
            lines.append(f"{name} & \\multicolumn{{5}}{{c}}{{\\itshape pending grid}} \\\\"); continue
        def fmt(s):
            m, d, _ = c[s]; return f"{m:.0f} ({d})"
        v, dm, pv = c.get("verdict", ("--", float("nan"), float("nan")))
        dd = f"{dm:+.0f}\\%, $p$={pv:.2f}" if dm == dm else "--"
        lines.append(f"{name} & {fmt('F')} & {fmt('T')} & {fmt('L')} & {dd} & {v} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    out = "paper/figures/best_achievable.tex"
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"wrote {out}\n" + "\n".join(lines))
    make_sweep_table()
    make_combined_table()


def make_combined_table():
    """Combined channel B (text+latent) vs the best single channel per game, held-out."""
    L = [r"% Auto-generated by scripts/make_best_achievable_table.py — do not edit by hand.",
         r"\begin{tabular}{lccccl}", r"\toprule",
         r"Game & best single & best $B$ & $\Delta_{B-\text{single}}$ & $p$ & effect \\",
         r"     & (T or L) & (T${+}$L) & (\%) & & \\", r"\midrule"]
    for name, tag in GAMES:
        dec = load(tag)
        if not dec or not any("B" in dec[l] for l in dec):
            L.append(f"{name} & \\multicolumn{{5}}{{c}}{{\\itshape pending}} \\\\"); continue
        hoT, _ = heldout_mean(dec, "T"); hoL, _ = heldout_mean(dec, "L"); hoB, _ = heldout_mean(dec, "B")
        if not (len(hoT) and len(hoL) and len(hoB)):
            L.append(f"{name} & \\multicolumn{{5}}{{c}}{{\\itshape pending}} \\\\"); continue
        if np.mean(hoT) >= np.mean(hoL): single, sv = "T", hoT
        else:                            single, sv = "L", hoL
        p = stats.ttest_ind(hoB, sv, equal_var=False).pvalue
        u = stats.mannwhitneyu(hoB, sv, alternative="two-sided").pvalue
        # % from the rounded means we print, for internal consistency (see best-achievable note).
        mB, mS = round(np.mean(hoB)), round(np.mean(sv))
        dm = 100 * (mB - mS) / mS if mS else float("nan")
        sig = min(p, u) < 0.05
        if dm < 0 and sig:   eff = r"\textbf{interferes}"
        elif dm > 0 and sig: eff = r"\textbf{complements}"
        else:                eff = "neutral"
        L.append(f"{name} & {np.mean(sv):.0f} ({single}) & {np.mean(hoB):.0f} & {dm:+.0f}\\% & {min(p,u):.2f} & {eff} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    open("paper/figures/combined.tex", "w").write("\n".join(L) + "\n")
    print("wrote paper/figures/combined.tex")


def make_sweep_table():
    """Raw per-decoder mean L-vs-T sweep (Appendix), one row per (game, decoder)."""
    order = [("greedy", "greedy_reconfirm"), ("$\\tau$=0.3", "sample_t03"),
             ("$\\tau$=0.5", "sample_t05"), ("$\\tau$=0.7", "sample_t07"),
             ("$\\tau$=1.0", "sample_t1"), ("$\\tau$=1.5", "sample_t15")]
    lab2suf = {l: s for l, s in order}
    L = [r"% Auto-generated by scripts/make_best_achievable_table.py — do not edit by hand.",
         r"{\small\begin{tabular}{llrrrl}", r"\toprule",
         r"Game & decoder & $F$ & $T$ & $L$ & $L$ vs $T$ \\", r"\midrule"]
    for name, tag in GAMES:
        dec = load(tag)
        first = True
        for lbl, suf in order:
            if lbl_key(lbl, dec) not in dec:
                continue
            d = dec[lbl_key(lbl, dec)]
            def m(s):
                v = [x for ep in d.get(s, {}).values() for x in ep]
                return np.mean(v) if v else float("nan")
            Fm, Tm, Lm = m("F"), m("T"), m("L")
            rel = "L>T" if Lm > Tm else ("L<T" if Lm < Tm else "L=T")
            g = name if first else ""
            L.append(f"{g} & {lbl} & {Fm:.0f} & {Tm:.0f} & {Lm:.0f} & {rel} \\\\")
            first = False
        if not first:
            L.append(r"\midrule")
    if L[-1] == r"\midrule":
        L[-1] = r"\bottomrule"
    else:
        L.append(r"\bottomrule")
    L.append(r"\end{tabular}}")
    open("paper/figures/decoder_sweep.tex", "w").write("\n".join(L) + "\n")
    print("wrote paper/figures/decoder_sweep.tex")


def lbl_key(lbl, dec):
    # map display label back to the internal decoder key used by load()
    keymap = {"greedy": "greedy", "$\\tau$=0.3": "t0.3", "$\\tau$=0.5": "t0.5",
              "$\\tau$=0.7": "t0.7", "$\\tau$=1.0": "t1.0", "$\\tau$=1.5": "t1.5"}
    return keymap.get(lbl, lbl)

if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    main()
